# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      env_file: '.env.prod'
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    volumes:
      - ./frankenphp/Caddyfile.prod:/etc/caddy/Caddyfile:ro
      # - ./frankenphp/conf.d/20-app.prod.ini:/usr/local/etc/php/app.conf.d/20-app.prod.ini:ro